### ISSUE TITLE
Rework the call to functions

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#40]
### Generic Issue

* xscen version: 0.2.x

### Description
`xscen` currently forces you to import and/or call each function by referring to the python file, which can become pretty cumbersome. We'd want to simplify that, e.g. going from `xscen.extraction.extract_dataset()` to `xscen.extract_dataset()`

As a bonus, we could use that occasion to rename files/function, if warranted, such as `xscen.regridding` or `xscen.finalize`

**Comment by Zeitsperre** [comment]
Should we add changes directly off of #35 ? I can open a branch based on that.

**Comment by RondeauG** [comment]
Sure, go ahead.

**Comment by juliettelavoie** [comment]
Suggestions for new names of files: all plural nouns?

biasadjust.py: biasadjustments
checkups.py: checkups
config.py:  configs
extraction.py:  extractions
scr_utils.py:    utils      (is scr_utils a thing?)
catalog.py:     catalogs
common.py:  X (put all the function here in utils)
ensembles.py:  ensembles
finalize.py:    conversions   (not convinced with this, clean_up does: unit conversion, calendar conversion, unstack nans, remove/add attrs)
indicators.py: indicators
io.py: ios (can this be plural?)
regridding.py: grids

**Comment by RondeauG** [comment]
- `scr_utils` was added by either @Zeitsperre or @aulemahal ? To be honest I'm not sure what it does, but I agree that we could probably combine it with `common`.

- Regarding the functions in `finalize`... Could they also simply fit in `utils`?

- Pretty sure that `io` cannot be plural. I'm fine with keeping it as is.

**Comment by Zeitsperre** [comment]
`scr_utils` is an @aulemahal innovation (and I kind of love it). For very long processes, you can make your script send out an email telling you when the process is complete. Very convenient.

For the renaming:

- biasadjust.py: biasadjustments -> _We could move this to `_biasadjustment` for now_
- checkups.py: checkups -> _Works for me_
- config.py: ~configs~ -> config  _Works for me_
- extraction.py: extractions -> _`extraction` sounds much better IMO_
- scr_utils.py: utils (is scr_utils a thing?) -> _I don't think it's a thing. This is more of `_scripting` or `_helpers` function._
- catalog.py: catalogs -> _`catalog` the singular verb feels more appropriate here, rather than `catalogs` the plural noun. We're performing operations_
- common.py: X (put all the function here in utils) -> _Works for me_
- ensembles.py: ensembles -> _Works for me_
- finalize.py: ~conversions (not convinced with this, clean_up does: unit conversion, calendar conversion, unstack nans, remove/add attrs)~ -> also put in utils -> _Works for me_
- indicators.py: indicators -> _Works for me_
- io.py: ~ios (can this be plural?)~ -> io -> _Works for me_
- regridding.py: grids -> _Not sure about this one. Actions would be better for modules names rather than nouns. What about `regrid`?_

**Comment by juliettelavoie** [comment]
I also love the email sending feature !

- I thought we wanted all files to be the same type of words (eg. plural nouns), but if you guys are ok with more variability, I would also keep `biasadjust` as is.  We can have plural nouns (`checkups`, `helpers`, `ensembles`, `indicators`) , actions (`biasadjust`, `extract`, `catalog`, `regrid`)  and singular nouns (`io`, `config`).

- I don't mind `regrid` but this is also the name of the function. We would have `xscen.regrid.regrid`. Would this create issues ? (same for `xscen.extract.extract`)

**Comment by RondeauG** [comment]
I'm fine with some variability. `biasadjust, extract, catalog, regrid` sounds nice to my ear.

We'd have `extract.extract_dataset`, which is fine. If `regrid.regrid` is a problem, we could do something similar ?

**Comment by Zeitsperre** [comment]
The latest changes rename `regrid` to `regrid_dataset` to reduce confusion.

If there are any functions that we would want in the top-most level, we can explicitly add them. e.g. `xscen.regrid()`. They can be hidden by default with `_{name}.py` files. We just need to know what we want.

**Comment by juliettelavoie** [comment]
I think we should put at least:

- xs.save_to_zarr
- xs.search_data_catalogs
- xs.extract_dataset
- xs.regrid_dataset
- xs.train
- xs.adjust
- xs.clean_up
- xs.rechunk
- xs.compute_indicators
- xs.ensemble_stats

(While I am here, I am also wondering if train/adjust should become train_dataset/adjust_dataset to fit the pattern and distinguish from xclim train and adjust ?)

What do you guys think?

**Comment by RondeauG** [comment]
I'd try to refrain from using `_dataset` everywhere. It makes the function names longer for no added value. If anything, I'd be for `xs.extract()` and `xs.regrid()` if we can find a way to make that work.

**Comment by RondeauG** [comment]
Closed with #41
