### ISSUE TITLE
HTML code is not displayed correctly on Gitlab

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xscen#46]
### Setup Information

- xscen version: 0.2.6-beta

### Description

This issue appears exclusive to the Jupyter Notebooks (`installation.rst` is displayed correctly). 

The colored boxes (e.g. "WARNING", "NOTE") aren't colored and aren't boxes. Italic and bold doesn't work either.

### Steps To Reproduce

I took the code from [here](https://gist.github.com/DanielKotik/4b81480c479a57e0dd13ac4d153e4451). 

It used to appear correctly in Github's interface. However, on Gitlab it instead appears as [plain text](https://scenario.gitlab.ouranos.ca/xscen/notebooks/getting_started.html#Searching-a-subset-of-datasets-within-DataCatalogs), or as the raw HTML code in the .ipynb.

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by RondeauG** [comment]
I found this, which might have the solution: https://about.gitlab.com/handbook/markdown-guide/#mix-html--markdown-markup

**Comment by aulemahal** [comment]
Related to this, those boxes also aren't colored boxes on the compiled doc that sphinx creates. I think this is due to differences between your source and what `nbsphinx` expects : https://nbsphinx.readthedocs.io/en/0.8.9/markdown-cells.html#Info/Warning-Boxes
i.e. : the class should be `class="alert alert-info"`, without "alert-block".

For the gitlab parser, I'm less confident on how we can fix it. Your link does appear to point to some option that is turned off, but the solution applies to pure markdown files, I'm not sure where to put the `{::options...}` block?

**Comment by RondeauG** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/27455 and https://gitlab.com/gitlab-org/gitlab/-/issues/18258 seem to indicate that it would be fixed for Jupyter notebooks... We'll have to investigate.

**Comment by RondeauG** [comment]
I removed the `alert-block` in the latest version (might have missed a few). It seems to have mostly worked, except that bold/italic HTML commands seem to be getting ignored. We're getting closer!

**Comment by RondeauG** [comment]
Not relevant anymore since #118
